# 2. NumPy 배열
* NumPy에는 ndarray라는 데이터 타입의 배열이 생성되다.
* list : [1,2,'hello'.[1,2,3]]
* ndarray는 같은 타입의 데이터만 저장할 수 있다.
* 많은 양의 데이터를 빠르게 처리하기 위해서
* Python의 list 보다 계산 속도가 빠르다.

In [1]:
# import 하기
import numpy as np

## 2-1. np.array() 함수로 ndarray 생성하기
### 1차원 배열 생성하기


In [2]:
#1차원 배열
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [3]:
#type 확인
type(arr)

numpy.ndarray

In [4]:
#튜플 확인
np.array((1,2,3,4))
#리스트로 전달할 수도 있다


array([1, 2, 3, 4])

In [5]:
#생성시 주의 할점
# np.array(1,2,3,4)
#array()에는 반드시 data가 1개 들어가야 한다!

In [6]:
#data type확인
arr.dtype
#함수 아니고 속성임!

dtype('int64')

In [7]:
#overflow test
# arr = np.array([2147483647,2,3,4])
arr = np.array([2147483648,2,3,4],dtype = np.int32) #?? 왜 에러가 안나지??
arr

array([-2147483648,           2,           3,           4], dtype=int32)

In [8]:
arr = np.array([1,2,3,4], dtype = float)
arr

array([1., 2., 3., 4.])

In [9]:
arr.dtype

dtype('float64')

In [10]:
# shape: 각 차원의 배열의 size (모양)
arr.shape #함수아니고 속성
#반환 값이 튜플
#(4,) 1차원은 comma 붙이고 null

(4,)

In [11]:
#size: 배열의 전체 element 수
arr.size#이 또한 함수 아니고 속성

4

In [12]:
# ndim: 차원의 수
arr.ndim

1

In [13]:
arr
#타입이 다르더라도, 업 케스팅이 된다!

array([1., 2., 3., 4.])

In [14]:
arr = np.array([1,2,3,3.14], dtype = int) #이렇게 하면 타입이 고정된다
arr

array([1, 2, 3, 3])

In [15]:
# > : big-endian(단위가 큰것부터 적는다), < : little-endian
arr = np.array([1,2,'1234'])
arr #업케스팅!! '<U21' default로 21바이트 주기

array(['1', '2', '1234'], dtype='<U21')

In [16]:
arr = np.array([1,2,'1234567890123456789012345678901234567890'])
arr #길이가 길어지니 주어진 바이트 수가 달라진다

array(['1', '2', '1234567890123456789012345678901234567890'], dtype='<U40')

In [17]:
# > : big-endian(단위가 큰것부터 적는다), < : little-endian
arr = np.array([1,2,'1234'],dtype = int)
arr #업케스팅!! '<U21' default로 21바이트 주기

array([   1,    2, 1234])

In [18]:
# 이미 있는 배열을 타입이 다른 배열로 생성하기
new_arr = arr.astype(int)
new_arr

array([   1,    2, 1234])

In [19]:
arr.dtype, new_arr.dtype

(dtype('int64'), dtype('int64'))

## 2차원 배열 생성하기

In [20]:
arr2 = np.array([[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]],dtype = float)
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [21]:
arr2.dtype, arr2.shape, arr2.size, arr2.ndim

(dtype('float64'), (3, 4), 12, 2)

In [22]:
new_arr = arr2.astype(int)
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2-2. np.arange() 함수로 생성하기

In [23]:
# 파이썬의 range
for i in range(0,10,2): #0~9
    print(i)

0
2
4
6
8


In [24]:
#1~10까지 ndarray
np.array([1,2,3,4,5,6,7,8,9,10]) #(X)
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1]

## 1차원 배열 생성하기

In [25]:
#회색 부분에서 a 누른면 위에 셀 생김
#1~10
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

## 2차원 배열 생성하기

In [26]:
# 0~11로 이루어진 배열 만들기
arr = np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
arr2 = arr.reshape((3,4))#튜플 사용 -> 해열 인듯
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
arr, arr2

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]))

In [29]:
# arr2 = arr.reshape((3,5))
# arr2

In [30]:
#원본 배열의 shape을 직접 변경하고자 할 경우
#not recommended
arr.shape

(12,)

In [31]:
arr.shape = (3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
#이제 부터 소개될 함수들은 그냥 있다 정도만 알면 됨

## 2-3. np.zeros() 함수

In [33]:
# 1차원 배열
arr = np.zeros(4,dtype = int)
arr

array([0, 0, 0, 0])

In [34]:
#2차원
arr2 = np.zeros((3,4),dtype = int)
arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

## 2-4. np.ones() 함수

In [35]:
#1차원 배열
arr = np.ones(4,dtype = int)
arr

array([1, 1, 1, 1])

In [36]:
#2차원 배열
arr2 = np.ones((3,4),dtype = int)
arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

### 2-5. np.linspace() 함수

In [37]:
arr = np.linspace(0,10,5)   
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [38]:
arr = np.linspace(0,10)
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [39]:
arr.shape

(50,)

In [40]:
arr2 = arr.reshape((10,5))
arr2

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653],
       [ 1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286],
       [ 3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918],
       [ 5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551],
       [ 7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184],
       [ 9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

### 2-6. np.full() 함수

In [41]:
#특정 값으로 배열을 생성할 경우
arr = np.full(4,10)
arr

array([10, 10, 10, 10])

In [42]:
arr2 = np.full((3,4),10)
arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [43]:
arr2 = np.full

### 2-7.np.eye() 함수

In [44]:
# 단위 행렬 (항등 행열) 만들어 줆
#주대각선의 값이 1, 나머지는 모두 0
arr = np.eye(5,dtype = int)
arr


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### 2-8. np.random을 이용

In [45]:
import numpy as np

In [46]:
arr = np.random.rand(4)
arr

array([0.0403472 , 0.90473623, 0.46185808, 0.7055727 ])

In [47]:
arr2 = np.random.rand(3,4)
arr2

array([[0.97550271, 0.69947642, 0.88543237, 0.62729484],
       [0.36635311, 0.21872891, 0.5222035 , 0.64548118],
       [0.41222466, 0.68126401, 0.49843475, 0.61392208]])

In [48]:
arr = np.random.randint(5, size = 10)
arr

array([0, 3, 4, 1, 3, 1, 3, 2, 4, 4])

In [49]:
arr2 = np.random.randint(1,5, size = (3,4))
arr2

array([[1, 1, 1, 4],
       [1, 2, 2, 3],
       [4, 2, 1, 2]])

In [50]:
#일정한 랜덤 값 만들기
np.random.seed(123)
np.random.rand(3,4)

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477],
       [0.71946897, 0.42310646, 0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752, 0.34317802, 0.72904971]])

## 2-9.Numpy 배열 Save & Load

In [51]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [52]:
np.save('my_arr',arr)
#saves to a binary file

In [53]:
new_arr = np.load('my_arr.npy')
new_arr

array([0, 1, 2, 3, 4])

In [55]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : 