# 3.연산

## 3.1 산술 연산

### 1차월 배열 (의 연산)

In [1]:
import numpy as np

In [2]:
a = np.arange(1,5) # 1~4
b = np.arange(5,9) # 5~8
a,b

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [3]:
a.shape, b.shape


((4,), (4,))

In [4]:
#배열 연산을 할려면 shape이 같아야 한다
a+b

array([ 6,  8, 10, 12])

In [5]:
a-b

array([-4, -4, -4, -4])

In [6]:
a*b

array([ 5, 12, 21, 32])

In [7]:
a/b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

### 2차원 배열(의 연산)

In [8]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
b = np.arange(7,13).reshape(2,3)
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [10]:
a+b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [11]:
a-b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [12]:
#단순 계산(이렇게 안함)
a*b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [13]:
a/b

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

### 행렬의 곱 (dot product)

In [14]:
#shape이 같은게 아니라, 첫번째 행렬의 열갯수와 굴째 행렬의 행 갯수가 동일해야함.
#(5,3) (3,4) 이렇게~
#https://ko.wikipedia.org/wiki/행렬_곱셈 참고!!

In [15]:
#중요
b = np.arange(7,13).reshape(3,2)
a,b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]]))

In [16]:
np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

### 3/22

In [17]:
import numpy as np

In [18]:
a.dot(b) #이것도 가능


array([[ 58,  64],
       [139, 154]])

In [19]:
#비교
print(a)
a<4

[[1 2 3]
 [4 5 6]]


array([[ True,  True,  True],
       [False, False, False]])

### 배열과 숫자(scalar)와의 연산 (broadcasting)

In [20]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [21]:
a+3

array([4, 5, 6])

In [22]:
a-3

array([-2, -1,  0])

In [23]:
a*3

array([3, 6, 9])

In [24]:
a/3

array([0.33333333, 0.66666667, 1.        ])

### 3-2. Aggregation 함수

#### 1차원 배열

In [25]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [26]:
# max 값 찾기
np.max(a)

5

In [27]:
a.max()

5

In [28]:
#최솟값 찾기
np.min(a)

1

In [29]:
a.min()

1

In [30]:
#배열의 합 구하기
np.sum(a)

15

In [31]:
#평균 구하기
np.mean(a,dtype = int)

3

In [32]:
a = np.array([1,2,3,4,100]) #튀어 나온값-> 이상치(Outlier)가 있는 경우 mean 값이 배열을 대표할 수 없음
np.mean(a)


22.0

In [33]:
#중앙값(중위값)
np.median(a)

3.0

In [34]:
#짝수의 경우
a = np.array([1,100,2,7])
np.median(a)

4.5

In [35]:
#std: 표준편차(standard deviation)
np.std(a)

41.91956583744636

#### 2차원 배열

In [36]:
a = np.arange(1,7).reshape(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.max(a)

6

In [38]:
np.min(a)

1

In [39]:
np.max(a,axis = 0) #모든 column(행)에 적용! like 0 

array([4, 5, 6])

In [40]:
np.max(a, axis=1)  #like -1

array([3, 6])

In [41]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.sum(a)

21

In [43]:
np.sum(a, axis=0)

array([5, 7, 9])

In [44]:
np.sum(a, axis=1)

array([ 6, 15])

In [45]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# cumsum
np.cumsum(a) #누적합

array([ 1,  3,  6, 10, 15, 21])

In [47]:
np.cumsum(a, axis = 0)

array([[1, 2, 3],
       [5, 7, 9]])

In [48]:
np.cumsum(a, axis = 1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [49]:
#corrcoef (상관계수)많이 쓰임!!
#두 변수 사이의 연관성을 나타내는 수치
np.corrcoef(a)

array([[1., 1.],
       [1., 1.]])

### 3월 24일

In [50]:
#corrcoef (상관계수)
#두 변수 사이의 연관성을 나타내는 수치
#키와 몸무게의 상관관계
h = [160,165, 170,180]
w = [47,55,70,85]
np.corrcoef(h,w)


array([[1.        , 0.99040485],
       [0.99040485, 1.        ]])

In [51]:
#검증
have = np.mean(h)
wave = np.mean(w)
have, wave

(168.75, 64.25)

In [52]:
a = np.sqrt(np.sum((h-have)**2))
a

14.79019945774904

In [53]:
b = np.sqrt(np.sum((w-wave)**2))
b

29.098969053902923

In [54]:
c = np.sum((h-have)*(w-wave))
c

426.25

In [55]:
r = c/(a*b)
r

0.990404850180661