# 4.정렬

## 4-1 1차원 정렬

In [1]:
import numpy as np

In [2]:
np.random.seed(100)
arr = np.random.randint(1,10, size = 10) #1~9, 10개
arr

array([9, 9, 4, 8, 8, 1, 5, 3, 6, 3])

In [3]:
#오름차순 정렬
#원본을 바꾸는건 아님!
b = np.sort(arr)
b

array([1, 3, 3, 4, 5, 6, 8, 8, 9, 9])

In [4]:
#내림 차순
c = np.sort(arr)
c[::-1]

array([9, 9, 8, 8, 6, 5, 4, 3, 3, 1])

In [5]:
arr.sort()#이렇게 하면 원본이 바뀜! but 가급적이면 원본 훼손 X
arr

array([1, 3, 3, 4, 5, 6, 8, 8, 9, 9])

## 4-2 2차원 배열

In [6]:
np.random.seed(100)
arr2 = np.random.randint(1,10,size = (3,4))
arr2

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3]])

In [7]:
np.sort(arr2) #axis=1랑 동일

array([[4, 8, 9, 9],
       [1, 3, 5, 8],
       [3, 3, 3, 6]])

In [8]:
np.sort(arr2, axis =0)

array([[6, 1, 3, 3],
       [8, 3, 4, 3],
       [9, 9, 5, 8]])

In [9]:
arr2.sort(axis = 1)
arr2

array([[4, 8, 9, 9],
       [1, 3, 5, 8],
       [3, 3, 3, 6]])

In [10]:
# index리턴하는 정렬함수: argsort
arr3 = np.random.randint(1,10,size = (3,4))
np.argsort(arr3) #axis =1 

array([[1, 0, 3, 2],
       [0, 2, 3, 1],
       [0, 2, 3, 1]])

In [11]:
np.argsort(arr3, axis = 1)

array([[1, 0, 3, 2],
       [0, 2, 3, 1],
       [0, 2, 3, 1]])

In [1]:
import numpy as np
np.argsort?

Signature: np.argsort(a, axis=-1, kind=None, order=None)
Docstring:
Returns the indices that would sort an array.

Perform an indirect sort along the given axis using the algorithm specified
by the `kind` keyword. It returns an array of indices of the same shape as
`a` that index data along the given axis in sorted order.

Parameters
----------
a : array_like
    Array to sort.
axis : int or None, optional
    Axis along which to sort.  The default is -1 (the last axis). If None,
    the flattened array is used.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort under the covers and, in general, the
    actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.
order : str or list of str, optional
    When `a` is an array with fields define