# 5.인덱싱과 슬라이싱

## 5-1. 인덱싱

In [1]:
import numpy as np

In [2]:
#1 차원 배열 인덱싱
arr = np.arange(1,11) #1~10까지
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[1], arr[4], arr[-1]

(2, 5, 10)

In [4]:
#2 차원 배열
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr2[0][1], arr2[1][2], arr2[2][3]
#다차원 인덱싱
arr2[0,1], arr2[1,2], arr2[2,3]

(2, 7, 12)

## 5-2 슬라이싱

In [6]:
# 1 차원 배열
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
#슬라이싱 [start:end:step]
arr[2:6]

array([3, 4, 5, 6])

In [8]:
#3~끝까지
arr[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#처음 부터 6까지
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [10]:
# 슬라이싱한 후 값을 변경하면 원본 배열에 영향을 미칠까?
new_arr = arr[2:6]
new_arr

array([3, 4, 5, 6])

In [11]:
new_arr[0] = 100
new_arr

array([100,   4,   5,   6])

In [12]:
arr
#엥? 원본이 바뀐다?################################################

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [13]:
copy_arr = np.copy(arr) #복사본 만들기
copy_arr

array([  1,   2, 100,   4,   5,   6,   7,   8,   9,  10])

In [14]:
arr[::2]

array([  1, 100,   5,   7,   9])

In [15]:
# 2차원 배열
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
#첫 번째 행 가져오기
arr2[0,:]

array([1, 2, 3, 4])

In [17]:
# 세 번째 열 가져오기
arr2[:,2]

array([ 3,  7, 11])

In [18]:
# 첫번째 행과 두번째 행 가져오기
arr2[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
# 두번째, 세번째 열 가져오기

In [20]:
arr2[:,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [21]:
arr2[:2,1:3]

array([[2, 3],
       [6, 7]])

## 5-3. Fancy 인덱싱

In [22]:
#1 차원
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
### [3,6,8]로된 1차원 배열 만들기 (규칙없는 뽑기!)
np.array([arr[2],arr[5],arr[7]])

array([3, 6, 8])

In [28]:
### fancy 인덱싱
# 인덱스로 #배열# 만들기
arr[[2,5,7]] #이것이 Fancy indexing!
#arr[i] 하면 i-1 번째 원소가 나오는것 같이, i 자리에 원하는 원소들을 나열한다!
#arr[2,5,7] #이것은 3차원! arr[2,5,7] = arr[2][5][7]

array([3, 6, 8])

In [29]:
#2차원 배열 Fancy indexing
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
#Fancy indexing을 이용하여 2차원 배열의 처음과 끝 배열 가져오기
arr2[[0,2],:]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [39]:
arr2[:,1:3]
arr2[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

### 5-4 Boolean 인덱싱

In [42]:
arr= np.arange(5)

In [43]:
condition = [True,True,False,False,True]

In [46]:
# Boolean indexing
arr[condition] #cond과 arr의 길이가 반드시 같아야 함!

array([0, 1, 4])

In [47]:
arr > 2

array([False, False, False,  True,  True])

In [48]:
arr[arr > 2]

array([3, 4])

In [49]:
#짝수 만 뽑기
arr[arr%2==0]

array([0, 2, 4])

In [59]:
#3초과 1미만인 수
arr[(arr<1) | (arr>3)] 

array([0, 4])

In [65]:
#2이상 4이하인 수
arr[(arr>=2) & (arr<=4)]#and 만으로는 안된다 & 괄호해야한다

array([2, 3, 4])