# 6. 실습

In [1]:
# numpy import하기
import numpy as np

## 6-1. NumPy 배열 생성

In [2]:
# np.array()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [15]:
# 1차원 배열의 데이터타입, 모양, 배열 전체 element의 수, 차원의 수 출력하기
arr = np.array([1,2,3,4,5])
arr.dtype,arr.shape,len(arr),arr.ndim

(dtype('int64'), (5,), 5, 1)

In [21]:
# np.array()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
np.array([10,20,30,40,50,60,70,80]).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [22]:
# np.arange()로 1차원 배열 [1, 2, 3, 4, 5] 생성 후 출력하기
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [23]:
# np.arange()로 아래 2차원 배열 생성 후 출력하기
# [[10, 20, 30, 40],
#  [50, 60, 70, 80]]
np.arange(10,90,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [25]:
# 주사위를 100번 던져서 나오는 숫자 배열 출력하기
np.random.randint(1,6,size = (5,20))

array([[1, 3, 5, 2, 3, 1, 4, 4, 3, 3, 4, 1, 1, 3, 3, 4, 4, 5, 3, 4],
       [1, 2, 1, 3, 1, 2, 4, 5, 4, 3, 5, 4, 2, 3, 4, 5, 1, 3, 1, 4],
       [1, 5, 5, 2, 4, 3, 4, 5, 1, 5, 3, 3, 4, 1, 4, 4, 3, 2, 5, 1],
       [2, 5, 2, 4, 5, 3, 5, 4, 5, 2, 4, 5, 4, 2, 5, 2, 5, 1, 2, 4],
       [4, 2, 2, 5, 1, 1, 1, 5, 1, 1, 4, 5, 2, 2, 1, 2, 3, 5, 1, 5]])

In [28]:
# np.random을 사용하여 랜덤 실수값으로 이루어진 (3, 4) 2차원 배열 생성
np.random.rand(3,4)

array([[0.97215338, 0.89208114, 0.4536284 , 0.4450571 ],
       [0.52223147, 0.88022444, 0.78806524, 0.38658406],
       [0.03733633, 0.77254647, 0.38661029, 0.39626821]])

## 6-2. 산술연산

In [29]:
# [1, 2, 3, 4, 5], [6, 7, 8, 9, 10] 1차원 배열 2개를 생성하고 출력하기
arr = np.arange(1,6)
arr2 = np.arange(6,11)
arr, arr2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [30]:
# 1차원 배열간 산술연산(덧셈, 뺄셈, 곱셈, 나눗셈) 하기
arr+arr2, arr-arr2, arr*arr2, arr/arr2

(array([ 7,  9, 11, 13, 15]),
 array([-5, -5, -5, -5, -5]),
 array([ 6, 14, 24, 36, 50]),
 array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ]))

In [31]:
# [[1, 2, 3, 4, 5]   [[11, 12, 13, 14, 15]
#  [6, 7, 8, 9, 10]], [16, 17, 18, 19, 20]] 2차원 배열 2개를 생성하고 출력하기
arr = np.arange(1,11).reshape(2,5)
arr2 = np.arange(11,21).reshape(2,5)
arr, arr2

(array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]))

In [32]:
# 2차원 배열간 산술연산(덧셈, 뺄셈, 나눗셈) 하기
arr+arr2, arr-arr2, arr*arr2, arr/arr2

(array([[12, 14, 16, 18, 20],
        [22, 24, 26, 28, 30]]),
 array([[-10, -10, -10, -10, -10],
        [-10, -10, -10, -10, -10]]),
 array([[ 11,  24,  39,  56,  75],
        [ 96, 119, 144, 171, 200]]),
 array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
        [0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ]]))

In [36]:
# 두번째 배열의 shape을 (5, 2)로 만들고 출력하기
arr2 = arr2.reshape(5,2)
arr2

array([[11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [37]:
# 행렬곱셈(dot product) 연산하기
np.dot(arr,arr2)

array([[245, 260],
       [620, 660]])

## 6-3. Aggregation 함수

In [39]:
# 1~10까지 이루어진 1차원 배열 생성하기
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
# 최대값, 최소값 출력하기
arr.max(), arr.min()

(10, 1)

In [46]:
# 배열요소의 합, 평균값 출력하기
arr.sum(), arr.mean()

(55, 5.5)

In [50]:
# 중앙값(중위값), 표준편차 출력하기
np.median(arr), np.std(arr)

(5.5, 2.8722813232690143)

In [48]:
# 1~20까지 이루어진 2차원 배열 (4, 5) 생성하기
arr2 = np.arange(1,21).reshape(4,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [53]:
# 각 행의 max값, min값 출력하기
arr2.max(axis = 1), arr2.max(axis = 1)

(array([ 5, 10, 15, 20]), array([ 5, 10, 15, 20]))

In [54]:
# 각 열의 max값, min값 출력하기
arr2.max(axis = 0), arr2.max(axis = 0)

(array([16, 17, 18, 19, 20]), array([16, 17, 18, 19, 20]))

In [55]:
# 각 행의 sum값 출력하기
arr2.sum(axis = 1)

array([15, 40, 65, 90])

In [56]:
# 각 열의 sum값 출력하기
arr2.sum(axis = 0)

array([34, 38, 42, 46, 50])

## 6-4. 정렬

In [62]:
# 1~100까지 랜덤 정수값을 갖는 1차원 배열 (10, ) 생성하기
# seed값 100부여하기
np.random.seed(100)
arr = np.random.randint(1,100,size = 10)
arr

array([ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99])

In [65]:
# 위 1차원 배열을 오름차순 정렬하기
arr.sort()
arr

array([ 9, 11, 25, 49, 53, 68, 80, 88, 95, 99])

In [68]:
# 위 1차원 배열을 내림차순 정렬하기
arr = arr[::-1]
arr

array([99, 95, 88, 80, 68, 53, 49, 25, 11,  9])

In [71]:
# 랜덤 seed값 100부여하기
# 1~100까지 랜덤 정수값을 갖는 2차원 배열 (5, 10) 생성하기
np.random.seed(100)
arr2 = np.random.randint(1,100,size = 50).reshape(5,10)
arr2

array([[ 9, 25, 68, 88, 80, 49, 11, 95, 53, 99],
       [54, 67, 99, 15, 35, 25, 16, 61, 59, 17],
       [10, 94, 87,  3, 28,  5, 32,  2, 14, 84],
       [ 5, 92, 60, 68,  8, 50, 48, 66, 62, 15],
       [56, 72, 81,  3, 95, 20, 99, 64, 54, 28]])

In [73]:
# 열 기준 정렬하기
arr2.sort(axis = 0)
arr2

array([[ 5, 25, 60,  3,  8,  5, 11,  2, 14, 15],
       [ 9, 67, 68,  3, 28, 20, 16, 61, 53, 17],
       [10, 72, 81, 15, 35, 25, 32, 64, 54, 28],
       [54, 92, 87, 68, 80, 49, 48, 66, 59, 84],
       [56, 94, 99, 88, 95, 50, 99, 95, 62, 99]])

In [74]:
# 행 기준 정렬하기
arr2.sort(axis = 1)
arr2

array([[ 2,  3,  5,  5,  8, 11, 14, 15, 25, 60],
       [ 3,  9, 16, 17, 20, 28, 53, 61, 67, 68],
       [10, 15, 25, 28, 32, 35, 54, 64, 72, 81],
       [48, 49, 54, 59, 66, 68, 80, 84, 87, 92],
       [50, 56, 62, 88, 94, 95, 95, 99, 99, 99]])

## 6-5. 인덱싱과 슬라이싱

In [79]:
# 0~14로 이루어진 2차원 배열 (3, 5) 생성하기
arr2 = np.arange(0,15).reshape(3,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [81]:
# 위 배열에서 7을 인덱싱하기
arr2[1,2]

7

In [83]:
# 위 배열에서 14를 인덱싱하기 (음수 인덱스 사용)
arr2[-1,-1]

14

In [84]:
# 위 배열에서 배열 [6, 7]을 슬라이싱하기
arr2[1,[1,2]]

array([6, 7])

In [86]:
# 위 배열에서 배열 [7, 12]을 슬라이싱하기
arr2[1:,2]

array([ 7, 12])

In [88]:
# 위 배열에서 [[3, 4], [8, 9]]을 슬라이싱하기
arr2[:2,3:]

array([[3, 4],
       [8, 9]])

In [90]:
# 위 배열에서 3의 배수 찾기
arr2[arr2%3==0]

array([ 0,  3,  6,  9, 12])

In [91]:
# 위 배열에서 4로 나누면 1이 남는 수 찾기
arr2[arr2%4==1]

array([ 1,  5,  9, 13])

In [92]:
# 위 배열에서 3의 배수이면서 4로 나누면 1이 남는 수 찾기
arr2[(arr2%3==0) & (arr2%4==1)]

array([9])

 ## 